### ISSUE TITLE
could not find driver (Connection: , SQL: select "label", "name" from "icons" limit 10)

### ISSUE THREAD

**Issue by Pok09** [tomatophp/filament-types#8]
After installation and configuration as mentioned in the readme, 
impossible to create a type, I get this error :
`could not find driver (Connection: , SQL: select "label", "name" from "icons" limit 10)`

![Tomto-types](https://github.com/user-attachments/assets/6bc140f7-e612-4710-8f69-c7c7e3ce90c4)

**Comment by 3x1io** [comment]
hi, @Pok09 we use sqlite to cache the data, so please make sure you have sqlite3 ex active on your PHP
